BUG:
Error: Could not find or load main class com.group.Backend.BackendApplication
Caused by: java.lang.ClassNotFoundException: com.group.Backend.BackendApplication